# Generated by Django 5.1.2 on 2025-03-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_checkotp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
