# Generated by Django 5.1.2 on 2025-03-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_discountcode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
